### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by markrey** [Symantec/hendrix#34]
Hi,

Amazing work on the Hendrix development.
I am interested in using as well ad contributing to the project.

What would be the project roadmap? I haven't seen any updates in a while.

Thanks
Mark

**Comment by ambud** [comment]
Here's a fork of the project, with further development: https://github.com/srotya/tau

Please feel free to open pull requests.

**Comment by markrey** [comment]
Thanks. Will you be pulling it back to Hendrix ?

**Comment by ambud** [comment]
Unfortunately no, the two projects are catered for different environments.

**Comment by markrey** [comment]
Thank for the quick feedback.
I will try Tau soon. Just going through installation procedure.

**Comment by ambud** [comment]
Artifacts are now published to Maven central: http://search.maven.org/#search%7Cga%7C1%7Ctau

**Comment by markrey** [comment]
Thanks @ambud . Can you please post docker instructions as well?

**Comment by ambud** [comment]
Here are the deployment steps: https://github.com/srotya/tau#deployment--download

@markrey please open an issue in Tau so we can close this issue.
